version: '3'

services:
  db:
    container_name: comics_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django
    logging:
      options:
        max-size: "50m"
        max-file: "2"
  comics_django:
    container_name: comics_django
    build: .
    env_file:
      - ./deploy/django.env
    command: supervisord -n -c deploy/supervisor.conf
    volumes:
      - .:/opt/django
      - ./deploy/certs:/etc/letsencrypt
      - ./deploy/static:/var/www/static
      - ./deploy/media:/var/www/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    logging:
      options:
        max-size: "50m"
        max-file: "2"